Add some stubs and missing symbols for CoreGraphics
darlinghq/darling-cocotron pull request #25
Opened 2023-03-17 11:15 UTC by dingari

2023-03-25 17:24 UTC, CuriousTommy requested changes

2023-03-25 17:24 UTC, CuriousTommy commented on CoreGraphics/include/CoreGraphics/CGWindowLevel.h
> +};
I already talked about this in the other PR, but i recommend sticking with how [Apple does in their documentation](https://developer.apple.com/documentation/coregraphics/cgwindowlevelkey?language=objc), or (even better) use `NS_ENUM`.

2023-03-25 17:24 UTC, CuriousTommy commented on CoreGraphics/include/CoreGraphics/CGGradient.h
> +typedef uint32_t CGGradientDrawingOptions;
Add in [kCGGradientDrawsBeforeStartLocation](https://developer.apple.com/documentation/coregraphics/cggradientdrawingoptions/kcggradientdrawsbeforestartlocation?language=objc) and [kCGGradientDrawsAfterEndLocation](https://developer.apple.com/documentation/coregraphics/cggradientdrawingoptions/kcggradientdrawsafterendlocation?language=objc).

https://developer.apple.com/documentation/coregraphics/cggradientdrawingoptions?language=objc

2023-03-26 14:23 UTC, dingari commented on CoreGraphics/include/CoreGraphics/CGWindowLevel.h
> +};
Using NS_ENUM resulted in a lot of compilation errors, but I've replaced these with CF_ENUM instead.

2023-03-26 14:24 UTC, dingari commented on CoreGraphics/include/CoreGraphics/CGGradient.h
> +typedef uint32_t CGGradientDrawingOptions;
I'm a bit confused, these constants were already defined, but I just added the typedef.

Anyway,  I've updated this enum declaration to use CF_ENUM, so it should be fine.

2023-03-26 17:24 UTC, CuriousTommy commented on CoreGraphics/include/CoreGraphics/CGGradient.h
> +typedef uint32_t CGGradientDrawingOptions;
> I'm a bit confused, these constants were already defined, but I just added the typedef.

Ah! My bad, I didn't see that those were already there.

2023-03-26 17:24 UTC, CuriousTommy commented on CoreGraphics/include/CoreGraphics/CGWindowLevel.h
> +};
> I've replaced these with CF_ENUM instead.

That's fine with me.

2023-03-26 17:27 UTC, merged