Add some stubs for missing symbols in CoreText
darlinghq/darling-cocotron pull request #26
Opened 2023-03-17 11:18 UTC by dingari

2023-03-25 17:13 UTC, CuriousTommy requested changes

2023-03-25 18:26 UTC, CuriousTommy requested changes

2023-03-25 18:26 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFrame.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFrame * CTFrameRef;
I recommend sticking with how [Apple declares `CTFrameRef` on their website](https://developer.apple.com/documentation/coretext/ctframeref/#declaration).

I don't recommend including stuff that doesn't exist on Apple's Documentation website (unless you have a good logical explanation for why it should exist, besides it existing in Apple's proprietary SDK).

2023-03-26 13:44 UTC, dingari commented on CoreText/include/CoreText/CTFrame.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFrame * CTFrameRef;
Noted, I just saw that this style already existed in [CTFont.h](https://github.com/darlinghq/darling-cocotron/blob/64aee1830f5e0ce319c9380f9dfd8db7bfdbc12b/CoreText/include/CoreText/CTFont.h#L26), so I figured it was OK.

The declaration from Apple's website won't compile as a drop-in replacement, do you want to change this line to the following?
```
typedef struct __CTFrame* CTFrameRef;
```

2023-03-26 18:00 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFrame.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFrame * CTFrameRef;
> Noted, I just saw that this style already existed in [CTFont.h](https://github.com/darlinghq/darling-cocotron/blob/64aee1830f5e0ce319c9380f9dfd8db7bfdbc12b/CoreText/include/CoreText/CTFont.h#L26), so I figured it was OK.

No worries. Matching how the other code is written is normally the right thing to do, but in this case, it not very obvious what `CF_BRIDGED_TYPE(id)` does or why it is needed. I rather play it safe and only add it in when we know why it is needed.

Maybe @ahyattdev had a good reason for adding in `CF_BRIDGED_TYPE(id)`, but I rather play it safe and not include it if it is not documented on Apple's website.

> The declaration from Apple's website won't compile as a drop-in replacement, do you want to change this line to the following?
> 
> ```
> typedef struct __CTFrame* CTFrameRef;
> ```

That's fine. I'm not sure why Apple's website doesn't show it as a pointer...

2023-03-26 18:13 UTC, dingari commented on CoreText/include/CoreText/CTFrame.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFrame * CTFrameRef;
I totally understand :)

2023-03-26 18:25 UTC, CuriousTommy requested changes

2023-03-26 18:25 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFrameSetter.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFramesetter * CTFramesetterRef;
I forgot to state this earlier, but there are other places where `CF_BRIDGED_TYPE(id)` should be removed as well.

After you are done with that, can you rebase (fixup) your `CF_BRIDGED_TYPE(id)` removal changes into 64aee1830f5e0ce319c9380f9dfd8db7bfdbc12b

2023-03-26 18:25 UTC, CuriousTommy commented on CoreText/include/CoreText/CTLine.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTLine * CTLineRef;
Same here

2023-03-26 18:25 UTC, CuriousTommy commented on CoreText/include/CoreText/CTRun.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTRun * CTRunRef;
Same here

2023-03-26 18:25 UTC, CuriousTommy commented on CoreText/include/CoreText/CTTypesetter.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTTypesetter * CTTypesetterRef;
Same here

2023-03-27 10:09 UTC, dingari commented on CoreText/include/CoreText/CTFrameSetter.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFramesetter * CTFramesetterRef;
Sure! Should be fixed now.

2023-03-27 10:18 UTC, dingari commented on CoreText/include/CoreText/CTFrameSetter.h
> +typedef const struct CF_BRIDGED_TYPE(id) __CTFramesetter * CTFramesetterRef;
Hm, I'm just now noticing a couple of other places where I used `CF_BRIDGED_TYPE`. I'll fix them now.

2023-03-27 17:14 UTC, merged