Stubs and symbols for iTerm2
darlinghq/darling-cocotron pull request #39
Opened 2024-06-16 13:08 UTC by sirnacnud

I attempted to get iTerm2 running under darling, these were the symbols/stubs I needed to implement in Cocotron. While I didn't manage to get iTerm2 fully running, I thought to push these up anyways.

Fixes specific missing symbol mentioned in: https://github.com/darlinghq/darling/issues/1350

### Stubs/Symbols Added
- **AppKit:** NSFontCollection, NSCandidateListTouchBarItem, NSPasteboardNameFind, NSPasteboardNameFont, NSScrubberSelectionStyle, NSScrubberItemView
- **CoreData:** NSSQLiteManualVacuumOption
- **CoreGraphics:** kCGWindowName, kCGWindowOwnerName

2024-06-16 14:21 UTC, CuriousTommy requested changes
Other then the above issues, the code looks good to me!

2024-06-16 14:21 UTC, CuriousTommy commented on AppKit/NSFontCollection.m
> +@implementation NSFontCollection
I think it might be a good idea to add the `- (NSMethodSignature *)methodSignatureForSelector:(SEL)aSelector` and `- (void)forwardInvocation:(NSInvocation *)anInvocation` implementation as well.

2024-06-16 14:21 UTC, CuriousTommy commented on AppKit/NSCandidateListTouchBarItem.m
> +@implementation NSCandidateListTouchBarItem
Same here (`methodSignatureForSelector:` & `forwardInvocation:`)

2024-06-16 14:21 UTC, CuriousTommy commented on AppKit/NSScrubberItemView.m
> +@end
Same here (`methodSignatureForSelector:` & `forwardInvocation:`)

2024-06-16 15:24 UTC, sirnacnud commented on AppKit/NSPasteboard.m
> +const NSPasteboardName NSPasteboardNameFont = @"NSPasteboardNameFont";
How do you look up the string values for these constants?

2024-06-16 15:26 UTC, CuriousTommy commented on AppKit/NSPasteboard.m
> +const NSPasteboardName NSPasteboardNameFont = @"NSPasteboardNameFont";
I made a test program on my Mac to print out the values:

```objc
int main(int argc, const char * argv[]) {
    NSLog(@"NSPasteboardNameFind: %@", NSPasteboardNameFind);
    NSLog(@"NSPasteboardNameFont: %@", NSPasteboardNameFont);
    NSLog(@"NSSQLiteManualVacuumOption: %@", NSSQLiteManualVacuumOption);
    NSLog(@"kCGWindowOwnerName: %@", kCGWindowOwnerName);
    NSLog(@"kCGWindowName: %@", kCGWindowName);
    
    return 0;
}
```

2024-06-16 22:02 UTC, CuriousTommy requested changes
Didn't catch the above earlier. I'm currently doing a build on my machine to make sure nothing breaks.

2024-06-16 22:02 UTC, CuriousTommy commented on AppKit/include/AppKit/NSCandidateListTouchBarItem.h
> +@interface NSCandidateListTouchBarItem<CandidateType> : NSTouchBarItem
On Apple's website, it's `<__covariant CandidateType>`

https://developer.apple.com/documentation/appkit/nscandidatelisttouchbaritem?language=objc

2024-06-19 16:00 UTC, CuriousTommy approved these changes
LGTM!

2024-06-19 16:12 UTC, merged