Add some CoreText stub definitions but keep most commented
darlinghq/darling-cocotron pull request #40
Opened 2024-09-21 19:37 UTC by jlucfarias

I've tried to add all constants of CTFont (unfortunatelfy I do not have time to add constants and stubs for other files) but I've keeped constants unused at this time commented to be uncommented later.

One suggestion is to move all frameworks from here (and other darling projects) to darling repo (or a darling specific repo for frameworks) to keep only one place with all frameworks. IMHO this is a more maintainable action to get darling project more active.
A lot of definitions can be get from the abandoned project [darling-coregraphics](https://github.com/darlinghq/darling-coregraphics/tree/master) and I used for reference for this changes.

Trying to fix [darling#797](https://github.com/darlinghq/darling/issues/797), [darling#798](https://github.com/darlinghq/darling/issues/798) and [darling#1527](https://github.com/darlinghq/darling/issues/1527),

2024-09-22 04:49 UTC, CuriousTommy requested changes
There are some changes I need you to fix first before I can merge this.

On a side note, is there a particular reason why you want to keep most of the new changes commented out? I think it would be better if we left them un-commented.

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/CTFont.m
> +const CFStringRef kCTFontStyleNameKey = @"kCTFontStyleNameKey";
Please don't change the old key value unless you can verify on a macOS machine that the new value is the correct one. I did a test on my Mac machine and the old value was the correct one.

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/CTFont.m
> +// CFStringRef kCTFontFeatureTooltipTextKey = @"kCTFontFeatureTooltipTextKey";
Are you using an auto formatting tool? It seems to be messing up the formatting of the commented out code...

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/CTFont.m
> +                                         CTFontDescriptorRef attributes)
I have mixed feelings about these formatting changes... I rather keep them the way they currently are.

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/CTFontDescriptor.m
> +// kCTFontPriorityAttribute = @"kCTFontPriorityAttribute";
Same here, looks like some weird formatting is going on here...

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/constants.c
> -const CFStringRef kCTFontFeaturesAttribute = CFSTR("NSFontFeaturesAttribute");
It's seems odd to me that you move this value, but you didn't move the other values (instead you made commented out copies of the other keys...)

I don't like the way you are handing this... you should either move these keys to the new location (uncommented), or leave them here.

2024-09-22 04:49 UTC, CuriousTommy commented on CoreText/CTFont.m
> +// @"kCTFontPostScriptCIDNameKey";
For the other values, here are the key values that macOS reports:

```suggestion
// const CFStringRef kCTFontCopyrightNameKey = @"CTFontCopyrightName";
// const CFStringRef kCTFontFamilyNameKey = @"CTFontFamilyName";
// const CFStringRef kCTFontSubFamilyNameKey = @"CTFontSubFamilyName";
const CFStringRef kCTFontStyleNameKey = @"CTFontSubFamilyName";
// const CFStringRef kCTFontUniqueNameKey = @"CTFontUniqueName";
const CFStringRef kCTFontFullNameKey = @"CTFontFullName";
// const CFStringRef kCTFontVersionNameKey = @"CTFontVersionName";
// const CFStringRef kCTFontPostScriptNameKey = @"CTFontPostScriptName";
// const CFStringRef kCTFontTrademarkNameKey = @"CTFontTrademarkName";
// const CFStringRef kCTFontManufacturerNameKey = @"CTFontManufacturerName";
// const CFStringRef kCTFontDesignerNameKey = @"CTFontDesignerName";
// const CFStringRef kCTFontDescriptionNameKey = @"CTFontDescriptionName";
// const CFStringRef kCTFontVendorURLNameKey = @"CTFontVendorURLName";
// const CFStringRef kCTFontDesignerURLNameKey = @"CTFontDesignerURLName";
// const CFStringRef kCTFontLicenseNameKey = @"CTFontLicenseNameName";
// const CFStringRef kCTFontLicenseURLNameKey = @"CTFontLicenseURLName";
// const CFStringRef kCTFontSampleTextNameKey = @"CTFontSampleTextName";
// const CFStringRef kCTFontPostScriptCIDNameKey = @"CTFontPostScriptCIDName";
```

2024-09-24 13:39 UTC, jlucfarias commented
@CuriousTommy I think I fixed all requested changes: reverted the formatting changes, uncomment constants and moved from constants.c to the new file.
My reasons for keep commented was that it is not used right now to issues I'm trying to fix, but I wanted to add these constants to be available to anyone that want to contribute with the project in the future

2024-10-26 18:44 UTC, CuriousTommy requested changes
Sorry for taking so long to review your new changes. Been feeling burned out lately...

2024-10-26 18:44 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFont.h
> +                                              CFStringRef attribute);
This should be one line, not two
```suggestion
CORETEXT_EXPORT CFTypeRef CTFontCopyAttribute(CTFontRef font, CFStringRef attribute);
```

2024-10-26 18:44 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFont.h
> +        /* CTFontDescriptorRef */ void *attributes);
Same here (Use `CTFontDescriptorRef` instead of `void*`)

2024-10-26 18:44 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFont.h
> +                                                  size_t count);
```suggestion
CORETEXT_EXPORT bool CTFontGetGlyphsForCharacters(CTFontRef font, const UniChar *characters, CGGlyph *glyphs, CFIndex count);
```

2024-10-26 18:44 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFont.h
> +                                                CGSize *advances, size_t count);
```suggestion
CORETEXT_EXPORT double CTFontGetAdvancesForGlyphs(CTFontRef font, CTFontOrientation orientation,
                                                const CGGlyph *glyphs,
                                                CGSize *advances, CFIndex count);
```

2024-10-29 05:03 UTC, CuriousTommy commented
@jlucfarias Did you get a chance to build and run your changes? I'm getting some errors:

```
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:189:14: error: redefinition of 'CTFontTableOptions'
  189 | typedef enum CTFontTableOptions : uint32_t {
      |              ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:124:30: note: previous definition is here
  124 | typedef CF_OPTIONS(uint32_t, CTFontTableOptions) {
      |                              ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:190:5: error: redefinition of enumerator 'kCTFontTableOptionNoOptions'
  190 |     kCTFontTableOptionNoOptions = 0,
      |     ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:125:5: note: previous definition is here
  125 |     kCTFontTableOptionNoOptions        = 0,
      |     ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:191:5: error: redefinition of enumerator 'kCTFontTableOptionExcludeSynthetic'
  191 |     kCTFontTableOptionExcludeSynthetic = (1 << 0) // Deprecated
      |     ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:126:5: note: previous definition is here
  126 |     kCTFontTableOptionExcludeSynthetic = 1,
      |     ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:192:3: error: typedef redefinition with different types ('enum (unnamed enum at /home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:189:14)' vs 'enum CTFontTableOptions')
  192 | } CTFontTableOptions;
      |   ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:124:30: note: previous definition is here
  124 | typedef CF_OPTIONS(uint32_t, CTFontTableOptions) {
      |                              ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:219:125: error: unknown type name 'CTFontSymbolicTraits'
  219 | CORETEXT_EXPORT CTFontRef CTFontCreateCopyWithSymbolicTraits(CTFontRef font, CGFloat size, const CGAffineTransform *matrix, CTFontSymbolicTraits symTraitValue, CTFontSymbolicTraits symTraitMask);
      |                                                                                                                             ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:219:161: error: unknown type name 'CTFontSymbolicTraits'
  219 | CORETEXT_EXPORT CTFontRef CTFontCreateCopyWithSymbolicTraits(CTFontRef font, CGFloat size, const CGAffineTransform *matrix, CTFontSymbolicTraits symTraitValue, CTFontSymbolicTraits symTraitMask);
      |                                                                                                                                                                 ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:228:17: error: unknown type name 'CTFontSymbolicTraits'
  228 | CORETEXT_EXPORT CTFontSymbolicTraits CTFontGetSymbolicTraits(CTFontRef font);
      |                 ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:260:72: error: unknown type name 'CTFontOrientation'
  260 | CORETEXT_EXPORT CGRect CTFontGetBoundingRectsForGlyphs(CTFontRef font, CTFontOrientation orientation, const CGGlyph *glyphs, CGRect *boundingRects, CFIndex count);
      |                                                                        ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:261:67: error: unknown type name 'CTFontOrientation'
  261 | CORETEXT_EXPORT double CTFontGetAdvancesForGlyphs(CTFontRef font, CTFontOrientation orientation,
      |                                                                   ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:282:17: error: unknown type name 'ATSFontRef'; did you mean 'CTFontRef'?
  282 | CORETEXT_EXPORT ATSFontRef CTFontGetPlatformFont(CTFontRef font, CTFontDescriptorRef  _Nullable *attributes); // Deprecated
      |                 ^~~~~~~~~~
      |                 CTFontRef
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:27:44: note: 'CTFontRef' declared here
   27 | typedef struct CF_BRIDGED_TYPE(id) KTFont *CTFontRef;
      |                                            ^
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:283:56: error: unknown type name 'ATSFontRef'; did you mean 'CTFontRef'?
  283 | CORETEXT_EXPORT CTFontRef CTFontCreateWithPlatformFont(ATSFontRef platformFont, CGFloat size, const CGAffineTransform *matrix, CTFontDescriptorRef attributes); // Deprecated
      |                                                        ^~~~~~~~~~
      |                                                        CTFontRef
/home/thomasa/Downloads/darling2/framework-include/CoreText/CTFont.h:27:44: note: 'CTFontRef' declared here
   27 | typedef struct CF_BRIDGED_TYPE(id) KTFont *CTFontRef;
      |                                            ^
3 warnings and 11 errors generated.
```

2024-12-08 23:37 UTC, jlucfarias commented
@CuriousTommy sorry for the late response. I couldn't build at the moment I sent my changes, but now I builded and fixed all errors related to Coretext changes. Please, try again

2024-12-15 23:39 UTC, CuriousTommy requested changes
There might be some additional fixes you might need to do, but here is what I found.

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/include/CoreText/CTFont.h
> +CORETEXT_EXPORT void CTFontDrawGlyphs(CTFontRef font, const CGGlyph *glyphs, const CGPoint *positions, size_t count, CGContextRef context);
Don't forget to include the header file for [`CGContextRef`](https://developer.apple.com/documentation/coregraphics/cgcontextref)

```
In file included from /home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:20:
/home/[user]/Downloads/darling2/framework-include/CoreText/CTFont.h:269:118: error: unknown type name 'CGContextRef'; did you mean 'CGFontRef'?
  269 | CORETEXT_EXPORT void CTFontDrawGlyphs(CTFontRef font, const CGGlyph *glyphs, const CGPoint *positions, size_t count, CGContextRef context);
      |                                                                                                                      ^~~~~~~~~~~~
      |                                                                                                                      CGFontRef
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
One thing to keep in mind is that not all return values are pointer based, so `nil` would not work here.

[`CGAffineTransform`](https://developer.apple.com/documentation/corefoundation/cgaffinetransform?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:154:12: error: returning 'void *' from a function with incompatible result type 'CGAffineTransform'
  154 |     return nil;
      |            ^~~
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here [`CTFontSymbolicTraits`](https://developer.apple.com/documentation/coretext/ctfontsymbolictraits?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:160:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'CTFontSymbolicTraits' (aka 'enum CTFontSymbolicTraits') [-Wint-conversion]
  160 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here [`CFStringEncoding`](https://developer.apple.com/documentation/corefoundation/cfstringencoding?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:219:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'CFStringEncoding' (aka 'unsigned int') [-Wint-conversion]
  219 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:243:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'unsigned int' [-Wint-conversion]
  243 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here [`CGRect`](https://developer.apple.com/documentation/corefoundation/cgrect?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:291:12: error: returning 'void *' from a function with incompatible result type 'CGRect' (aka 'struct CGRect')
  291 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here [`CGRect`](https://developer.apple.com/documentation/corefoundation/cgrect?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:314:12: error: returning 'void *' from a function with incompatible result type 'CGRect' (aka 'struct CGRect')
  314 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
>      return nil;
Same here [`CGGlyph`](https://developer.apple.com/documentation/coregraphics/cgglyph?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:283:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'CGGlyph' (aka 'unsigned short') [-Wint-conversion]
  283 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
>      return nil;
Same here [`CFIndex`](https://developer.apple.com/documentation/corefoundation/cfindex?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:365:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'CFIndex' (aka 'long') [-Wint-conversion]
  365 |     return nil;
      |
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
>      return nil;
Same here [`ATSFontRef`](https://developer.apple.com/documentation/coretext/atsfontref?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:385:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'ATSFontRef' (aka 'unsigned int') [-Wint-conversion]
  385 |     return nil;
      |            ^~~
```

2024-12-15 23:39 UTC, CuriousTommy commented on CoreText/CTFont.m
> +    return nil;
Same here [`CFTypeID`](https://developer.apple.com/documentation/corefoundation/cftypeid?language=objc)

```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:418:12: error: incompatible pointer to integer conversion returning 'void *' from a function with result type 'CFTypeID' (aka 'unsigned long') [-Wint-conversion]
  418 |     return nil;
      |            ^~~
```

2024-12-30 20:42 UTC, CuriousTommy requested changes
Just a few more fixes:

https://github.com/darlinghq/darling-cocotron/blob/master/CoreGraphics/include/CoreGraphics/CGContext.h#L22
```
/home/[user]/Downloads/darling2/framework-include/CoreGraphics/CGContext.h:23:32: error: typedef redefinition with different types ('struct CF_BRIDGED_TYPE' vs 'id')
   23 | typedef struct CF_BRIDGED_TYPE(id) O2Context *CGContextRef;
      |                                ^
```

https://github.com/darlinghq/darling-cocotron/blob/master/CoreText/stubs.c#L3-L6
```
[ 45%] Linking C shared library CoreText
ld: warning: OS dylibs should not add rpaths (linker option: -rpath) (Xcode build setting: LD_RUNPATH_SEARCH_PATHS)
duplicate symbol '_CTFontCreateWithFontDescriptor' in:
    CMakeFiles/CoreText.dir/CTFont.m.o
    CMakeFiles/CoreText.dir/stubs.c.o
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

2024-12-30 20:42 UTC, CuriousTommy commented on CoreText/CTFont.m
> +const CFStringRef kCTFontCopyrightNameKey = CFSTR("CTFontCopyrightName")
```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFont.m:24:73: error: expected ';' after top level declarator
   24 | const CFStringRef kCTFontCopyrightNameKey = CFSTR("CTFontCopyrightName")
      |                                                                         ^
      | 
```

2024-12-30 20:42 UTC, CuriousTommy commented on CoreText/CTFontDescriptor.m
> +const CFStringRef kCTFontPriorityAttribute = CFSTR("NSCTFontPriorityAttribute");
```
/home/[user]/Downloads/darling2/src/external/cocotron/CoreText/CTFontDescriptor.m:7:41: error: call to undeclared function 'CFSTR'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
    7 | const CFStringRef kCTFontURLAttribute = CFSTR("NSCTFontFileURLAttribute");
      |
```

2025-04-28 01:48 UTC, Lazerbeak12345 commented
I don't have much experience building darling from source, but I think I'm getting a build error on this branch.

If I'm the only one with the error then I'm likely just missing something.

(when building all of darling, but with this PR checked out in the correct submodule) it succeeds with this:

`cmake -DCOMPONENTS=system -DCMAKE_BUILD_TYPE=Debug ..`

and fails with this

`cmake -DCOMPONENTS=gui -DCMAKE_BUILD_TYPE=Debug ..`

End of the build log when it fails is:

```log
2 warnings generated.
2 warnings generated.
2 warnings generated.
/home/nate/projects/darling/src/external/iokitd/src/IOService.mm:55:13: warning: instance method '-isEqualToString:' not found (return type defaults to 'id') [-Wobjc-method-access]
   55 |                         if ([key isEqualToString: @"IONameMatch"])
      |                                  ^~~~~~~~~~~~~~~
/home/nate/projects/darling/framework-include/Foundation/NSObjCRuntime.h:291:8: note: receiver is instance of class declared here
  291 | @class NSString, Protocol;
      |        ^
2 warnings generated.
3 warnings generated.
[ 92%] Built target Security_i386
2 warnings generated.
2 warnings generated.
[ 92%] Linking CXX shared library HIServices
ld: warning: static initializer found in 'CMakeFiles/HIServices.dir/src/HIServices.c.o'. Use -no_inits to make this an error.  Use -no_warn_inits to suppress warning
ld: warning: static initializer found in 'CMakeFiles/HIServices.dir/src/HIServices.c.o'. Use -no_inits to make this an error.  Use -no_warn_inits to suppress warning
[ 92%] Built target HIServices
2 warnings generated.
2 warnings generated.
[ 92%] Linking CXX executable iokitd
[ 92%] Built target iokitd
make: *** [Makefile:136: all] Error 2
```

The latter _does_ succeed without the changes from this branch.

2025-04-28 02:05 UTC, CuriousTommy commented
That to be expected, there are some fixes that jlucfarias needs to do before I can merge this.

2025-04-28 02:11 UTC, Lazerbeak12345 commented
yep! I was just hoping to give it a spin, see if I notice anything, if it works etc.

2025-05-02 02:12 UTC, Lazerbeak12345 commented
If I apply this patch to this branch, the branch compiles successfully, and my test program prints this near the end of it's logs (it crashes because of stubs, instead of missing symbols, so this is desired).

```patch
diff --git a/CoreGraphics/include/CoreGraphics/CGContext.h b/CoreGraphics/include/CoreGraphics/CGContext.h
index 12a110e5..973670ba 100644
--- a/CoreGraphics/include/CoreGraphics/CGContext.h
+++ b/CoreGraphics/include/CoreGraphics/CGContext.h
@@ -18,6 +18,7 @@ AN ACTION OF CONTRACT,TORT OR OTHERWISE,ARISING FROM,OUT OF OR IN CONNECTION
 WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. */

 #import <CoreGraphics/CoreGraphicsExport.h>
+#import <CoreFoundation/CFBase.h>

 typedef struct CF_BRIDGED_TYPE(id) O2Context *CGContextRef;
```

Here's the (successful) stubs in-use, logged from the software:

```log
STUB CTFontCollectionRef CTFontCollectionCreateFromAvailableFonts(CFDictionaryRef)
STUB CFArrayRef CTFontCollectionCreateMatchingFontDescriptors(CTFontCollectionRef)
```

This patch is needed because the dependency was removed from `CoreText/include/CoreText/CTFontDescriptor.h`, and is next needed in `CoreGraphics/include/CoreGraphics/CGContext.h`

Thanks so much for working on this!

2025-05-03 21:54 UTC, jlucfarias commented
Sorry for the late response. Many thanks, @Lazerbeak12345. I was unable to search the solution for the error that CuriousTommy noticed and your patch worked like a charm. I've posted and made you as co-author because the change was your, not mine. @CuriousTommy, please review again

2025-05-10 04:30 UTC, CuriousTommy commented
I was able to build without any build failures occurring. My only final request is that your combine your commits. After that, I'll merge it in.

2025-05-10 13:03 UTC, jlucfarias commented
@CuriousTommy done

2025-05-10 17:46 UTC, merged

2025-05-10 17:47 UTC, CuriousTommy commented
Thank you for your contribution!